### ISSUE TITLE
Application don't show any NFT with ledger wallet

### ISSUE THREAD

**Issue by gades** [mytonwalletorg/mytonwallet#43] opened 2024-01-19 19:35 UTC
<img width="1286" alt="Screenshot 2024-01-19 at 21 34 15" src="https://github.com/mytonwalletorg/mytonwallet/assets/4200730/09c7d714-fe57-44fe-b459-3eedf282459b">

https://tonscan.org/address/UQDN8zfNmmUE77Eha-ZhD2mBuOrCI1fN-LEdSfS2uJLQNSX0#nfts

**Comment by mytonwalletorg** [comment] 2024-01-21 14:35
This is by design. Ledger for TON currently does not support NFTs. Once it's fixed on that side, we will add the tab in our wallet.

**Closed** 2024-01-21 14:35 UTC

**Comment by 0xsarawut** [comment] 2026-03-29 11:10
> <img alt="Screenshot 2024-01-19 at 21 34 15" width="1286" src="https://private-user-images.githubusercontent.com/4200730/298177751-09c7d714-fe57-44fe-b459-3eedf282459b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ3ODI4ODAsIm5iZiI6MTc3NDc4MjU4MCwicGF0aCI6Ii80MjAwNzMwLzI5ODE3Nzc1MS0wOWM3ZDcxNC1mZTU3LTQ0ZmUtYjQ1OS0zZWVkZjI4MjQ1OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAzMjlUMTEwOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY4NzY2ZTVmMmMxMmJmZjgwNzczNDQ3YzJlMDgwZDQwYzNhNzIxYTYzODEyMzllMzFiZWViN2VmM2E4NWIwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YALlzdeZkQoyg8wbrEOtWzOGOQU-y9K6FUtLEW0HDSE">
> https://tonscan.org/address/UQDN8zfNmmUE77Eha-ZhD2mBuOrCI1fN-LEdSfS2uJLQNSX0#nfts

https://my.tt/nft/EQAgOkQFna9qiwXhfwbvR0yjWA6x9TpXUTrF_cBnWbMapa8V
